server:
    port: 8050
spring:
  application:
    name: productos

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true

